version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: horizon-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: horizon-flask
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: horizontravels
    depends_on:
      - db
    volumes:
      - ./app:/app

volumes:
  db_data:
